# Generated by Django 3.0.8 on 2020-08-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addbooks', '0002_books_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='approved',
            field=models.IntegerField(default=0),
        ),
    ]
