# Generated by Django 3.0.8 on 2020-08-20 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 13, 9, 23, 724613)),
        ),
    ]
